# Generated by Django 2.2.10 on 2020-04-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='data_inicio',
            field=models.DateField(default='2020-04-03'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projeto',
            name='situacao',
            field=models.IntegerField(choices=[[1, 'Em Andamento'], [2, 'Suspenso'], [3, 'Finalizado']], default=1),
        ),
    ]
