# Generated by Django 2.2.10 on 2020-04-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_certificado_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='elemento',
            name='simbolo',
            field=models.CharField(default='', max_length=2, verbose_name='Símbolo'),
            preserve_default=False,
        ),
    ]
