# Generated by Django 2.2.10 on 2020-04-03 18:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_elemento_simbolo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificadoelemento',
            options={'ordering': ['certificado', 'elemento'], 'verbose_name_plural': 'Dados dos Certificados'},
        ),
        migrations.AlterModelOptions(
            name='elemento',
            options={'ordering': ['simbolo']},
        ),
        migrations.AddField(
            model_name='certificadoelemento',
            name='concentracao',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificadoelemento',
            name='incerteza_expandida',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
