# Generated by Django 2.2.10 on 2020-04-08 19:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20200403_1444'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificado',
            options={'ordering': ['descricao'], 'verbose_name': 'Certificado', 'verbose_name_plural': 'Certificados'},
        ),
        migrations.AlterModelOptions(
            name='certificadoelemento',
            options={'ordering': ['certificado', 'elemento'], 'verbose_name': 'Dado do Certificado', 'verbose_name_plural': 'Dados dos Certificados'},
        ),
        migrations.AlterModelOptions(
            name='elemento',
            options={'ordering': ['simbolo'], 'verbose_name': 'Elemento', 'verbose_name_plural': 'Elementos'},
        ),
        migrations.AlterModelOptions(
            name='medicao',
            options={'ordering': ['-data'], 'verbose_name': 'Medição', 'verbose_name_plural': 'Medições'},
        ),
        migrations.AlterModelOptions(
            name='projeto',
            options={'ordering': ['descricao'], 'verbose_name': 'Projeto', 'verbose_name_plural': 'Projetos'},
        ),
        migrations.AddField(
            model_name='elemento',
            name='fracao_massa',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Fração de massa'),
        ),
        migrations.AddField(
            model_name='elemento',
            name='tipo_fracao_massa',
            field=models.IntegerField(choices=[[0, '%'], [1, 'PPM'], [2, 'PPB']], default=0),
        ),
        migrations.AlterField(
            model_name='certificadoelemento',
            name='concentracao',
            field=models.DecimalField(decimal_places=5, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Concentração'),
        ),
        migrations.AlterField(
            model_name='certificadoelemento',
            name='incerteza_expandida',
            field=models.DecimalField(decimal_places=5, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Incerteza Expandida'),
        ),
    ]
