# Generated by Django 2.2.10 on 2020-04-08 19:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20200408_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elemento',
            name='fracao_massa',
        ),
        migrations.RemoveField(
            model_name='elemento',
            name='tipo_fracao_massa',
        ),
        migrations.AddField(
            model_name='certificadoelemento',
            name='fracao_massa',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Fração de massa'),
        ),
        migrations.AddField(
            model_name='certificadoelemento',
            name='tipo_fracao_massa',
            field=models.IntegerField(choices=[[0, '%'], [1, 'PPM'], [2, 'PPB']], default=0),
        ),
    ]
