# Generated by Django 2.2.10 on 2020-04-13 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_auto_20200408_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicao',
            name='elemento',
        ),
        migrations.AddField(
            model_name='medicao',
            name='dados_elemento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portal.CertificadoElemento'),
            preserve_default=False,
        ),
    ]
