# Generated by Django 2.2.10 on 2020-04-13 18:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_auto_20200413_1429'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificadoelemento',
            options={'ordering': ['elemento', 'certificado'], 'verbose_name': 'Dado do Certificado', 'verbose_name_plural': 'Dados dos Certificados'},
        ),
        migrations.AddField(
            model_name='medicao',
            name='concentracao_medicao',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Concentração Médição'),
        ),
    ]
