# Generated by Django 2.2.10 on 2020-04-13 18:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_auto_20200413_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicao',
            name='incerteza_expandida_combinada',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Incerteza Expandida Combinada da Medição'),
        ),
        migrations.AddField(
            model_name='medicao',
            name='incerteza_expandida_medicao',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Incerteza Expandida da Medição'),
        ),
        migrations.AddField(
            model_name='medicao',
            name='incerteza_padrao_medicao',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Incerteza Padrão da Medição'),
        ),
        migrations.AlterField(
            model_name='medicao',
            name='concentracao_medicao',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Concentração da Medição'),
        ),
    ]
