# Generated by Django 2.2.10 on 2020-04-13 18:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_auto_20200413_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificadoelemento',
            name='incerteza_combinada',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Incerteza Combinada'),
        ),
        migrations.AddField(
            model_name='certificadoelemento',
            name='incerteza_confianca',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Incerteza Confiança'),
        ),
        migrations.AddField(
            model_name='certificadoelemento',
            name='incerteza_padrao',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Incerteza Padrão'),
        ),
        migrations.AlterField(
            model_name='certificadoelemento',
            name='incerteza_expandida',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Incerteza Expandida'),
        ),
    ]
