# Generated by Django 2.2.10 on 2020-10-14 19:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_auto_20200827_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificadoelemento',
            name='incerteza_confianca',
        ),
        migrations.AddField(
            model_name='certificadoelemento',
            name='intervalo_confianca',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Intervalo de Confiança'),
        ),
        migrations.AddField(
            model_name='medicao',
            name='intervalo_confianca_medicao',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, help_text='Dados da medição', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Intervalo de Confiança'),
        ),
        migrations.AlterField(
            model_name='medicao',
            name='tipo_incerteza',
            field=models.IntegerField(choices=[[2, 'Intervalo de Confiança'], [3, 'Incerteza Combinada'], [0, 'Incerteza Expandida'], [1, 'Incerteza Padrão']], default=0),
        ),
    ]
