# Generated by Django 2.2.10 on 2020-10-14 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_auto_20201014_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicao',
            name='descricao',
        ),
    ]
