# Generated by Django 2.2.10 on 2020-10-16 21:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_remove_medicao_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificadoelemento',
            name='concentracao',
            field=models.DecimalField(decimal_places=5, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Concentração'),
        ),
        migrations.AlterField(
            model_name='certificadoelemento',
            name='incerteza_combinada',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Incerteza Combinada'),
        ),
        migrations.AlterField(
            model_name='certificadoelemento',
            name='incerteza_expandida',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Incerteza Expandida'),
        ),
        migrations.AlterField(
            model_name='certificadoelemento',
            name='incerteza_padrao',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Incerteza Padrão'),
        ),
        migrations.AlterField(
            model_name='certificadoelemento',
            name='intervalo_confianca',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Intervalo de Confiança'),
        ),
        migrations.AlterField(
            model_name='medicao',
            name='concentracao_medicao',
            field=models.DecimalField(decimal_places=5, default=0, help_text='Dados da medição', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Concentração'),
        ),
        migrations.AlterField(
            model_name='medicao',
            name='incerteza_expandida_combinada',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, help_text='Dados da medição', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Incerteza Expandida Combinada'),
        ),
        migrations.AlterField(
            model_name='medicao',
            name='incerteza_expandida_medicao',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, help_text='Dados da medição', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Incerteza Expandida'),
        ),
        migrations.AlterField(
            model_name='medicao',
            name='incerteza_padrao_medicao',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, help_text='Dados da medição', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Incerteza Padrão'),
        ),
        migrations.AlterField(
            model_name='medicao',
            name='intervalo_confianca_medicao',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, help_text='Dados da medição', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Intervalo de Confiança'),
        ),
    ]
