# Generated by Django 2.2.10 on 2020-10-17 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_auto_20201016_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificadoelemento',
            name='tipo_concentracao',
            field=models.IntegerField(choices=[[0, 'Certificado'], [1, 'Informado'], [2, 'Referência']], default=0, verbose_name='Tipo Concentração'),
        ),
    ]
