# Generated by Django 2.2.10 on 2020-10-17 22:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0020_auto_20201017_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificadoelemento',
            name='incerteza_expandida',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Incerteza Expandida'),
        ),
    ]
