# Generated by Django 2.2.10 on 2020-10-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0021_auto_20201017_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicao',
            name='tipo_fracao_massa',
            field=models.IntegerField(choices=[[0, '%'], [1, 'PPM'], [2, 'PPB']], default=1, verbose_name='Tipo Fração de Massa'),
        ),
    ]
